### PR TITLE
Update reporter_darwin.go

### PR DESCRIPTION
**Pull request by hichentang**

### CODE REVIEW

**Comment by bengrewell** [comment]
I don't see any changes to code here besides an empty line? Am I missing something?

**Comment by hichentang** [comment]
> I don't see any changes to code here besides an empty line? Am I missing something?

just remove the conflict message from the code comments, nothing wrong with the code itself :)

**Comment by boyvinall** [comment]
@bengrewell check e.g. https://github.com/BGrewell/go-iperf/blob/8e5fc7da0df5ce08f519219b9177a0a24ff8820c/reporter_darwin.go#L13

Would love to see this get merged

**Comment by boyvinall** [comment]
Thanks!

**Pull request merged**
